project:
  type: book

book:
  title: "SC_Assignment1"
  author: "Liam Erasmus"
  chapters:
    - index.qmd
    -  Practical1.qmd
    - 05Feb_Exercises.qmd
    - 06Feb_Exercises.qmd
  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
